### ISSUE TITLE
termshark does not support extcap interfaces

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#78]
## Problem 

termshark does not support extcap interfaces

### Interface list

```bash
$ tshark -D
1. en0 (Wi-Fi)
2. p2p0
3. awdl0
4. bridge0 (Thunderbolt Bridge)
5. utun0
6. en1 (Thunderbolt 1)
7. en2 (Thunderbolt 2)
8. lo0 (Loopback)
9. gif0
10. stf0
11. XHC20
12. ciscodump (Cisco remote capture)
13. randpkt (Random packet generator)
14. sshdump (SSH remote capture)
15. udpdump (UDP Listener remote capture)
```

### Current Behavior

termshark errors as if there is a sudo error when a randpkt interface is sent in:

```bash
$ sudo termshark -i randpkt
(The termshark UI will start when packets are detected...)
Cannot capture on device randptk: exit status 1 (exit code 1)
See https://termshark.io/no-root for more info.

$ sudo termshark -i 13
(The termshark UI will start when packets are detected...)
Cannot capture on device randpkt: exit status 1 (exit code 1)
See https://termshark.io/no-root for more info.
```

### Expected Behavior

termshark to support randpkt interface

### Comparisons to what tshark does 

```
$ tshark -i randpkt -c 5
Capturing on 'Random packet generator: randpkt'
    1   0.000000 208.21.2.184 → 10.1.1.99    DNS  916 Unknown operation (6) response 0x3088 Unknown error (14)[Malformed Packet] ff:ff:ff:ff:ff:ff ← 01:01:01:01:01:01
    2   1.000000 208.21.2.184 → 10.1.1.99    DNS  3583 Unknown operation (11) response 0x300d Name exists[Malformed Packet] ff:ff:ff:ff:ff:ff ← 01:01:01:01:01:01
    3   2.000000 208.21.2.184 → 10.1.1.99    DNS  3116 Unknown operation (7) response 0x3000 Refused[Malformed Packet] ff:ff:ff:ff:ff:ff ← 01:01:01:01:01:01
    4   3.000000 208.21.2.184 → 10.1.1.99    DNS  2365 Unknown operation (15) response 0x3060 Unknown error (13)[Malformed Packet] ff:ff:ff:ff:ff:ff ← 01:01:01:01:01:01
    5   4.000000 208.21.2.184 → 10.1.1.99    DNS  2803 Zone change notification response 0x30d6 RRset does not exist[Malformed Packet] ff:ff:ff:ff:ff:ff ← 01:01:01:01:01:01
5 packets capture
$ 
```

## Context

```bash
# version info
$ termshark -vv
termshark v2.0.2++
using tshark 3.0.7 (from /Applications/Wireshark.app/Contents/MacOS/tshark)
```

Found when trying to test multiple network interfaces, #75.

Marking as both bug and feature request because it's technically another feature, but expectation is that all interfaces that work with tshark will work with termshark. 

MacOS 10.14; amd64.

----

# Update (per discussion)

Feature request here is to default to dumpcap (current behavior), but if an interface is not recognized:

1. Check tshark for virtual interfaces (both numbered and extcap by name)
2. If tshark has that interface, change packet reader to tshark and read that interface
3. If not, error for unrecognized interface as usual

**Comment by gcla** [comment]
Hi - thanks, I'd noticed this but am not sure the best course of action. Can you try changing this in, or adding it to `$XDG_CONFIG_HOME/termshark.toml`:

```toml
[main]
  dumpcap = "tshark"
```

Then e.g.

```bash
termshark -i randpkt
```

Maybe I should just make `tshark` the default if that config option isn't provided. Termshark is supposed to be a tui for tshark after all...

**Comment by pocc** [comment]
🎄Happy Holidays Graham! 🎄

$XDG_CONFIG_HOME is configured to `$HOME/.config` on my machine, where there was no termshark.toml configured.

Same error:
```bash
$ sudo termshark -i randpkt
(The termshark UI will start when packets are detected...)
Cannot capture on device randpkt: exit status 1 (exit code 1)
See https://termshark.io/no-root for more info.
```

**Comment by gcla** [comment]
Happy hols to you too! :-)

I messed up the path, do you have a `$XDG_CONFIG_HOME/termshark/termshark.toml` file?

**Comment by pocc** [comment]
`termshark` is not a folder in $XDG_CONFIG_HOME (and initially wasn't defined for me - I am defining per shell session). I am using the macos default (~/.config) where many other programs store their files. Is there some other folder I should look?

**Comment by pocc** [comment]
I agree with you though - dumpcap only detects physical interfaces, so changing packet reader to tshark will likely solve.

**Comment by gcla** [comment]
Dug into this a bit further. I use this library to manage the choice of config and cache directories on the filesystem: https://github.com/shibukawa/configdir. It says that on macOS, the config dir should be `${HOME}/Library/Application Support` and the cache dir should be `${HOME}/Library/Caches`. So maybe there's a `termshark.toml` file in `~/Library/Application Support/termshark`? I think my `$XDG_CONFIG_HOME` was probably a bum steer on macOS.

I should've saved up for a macbook this holiday season...

**Comment by gcla** [comment]
Hi - I made the default live capture tool tshark instead of dumpcap. In doing so, I realized I should've made the command override approach in the toml file a little more flexible, so at the moment, whatever command is run for the live capture has to understand this invocation:

```
<mylivecapture> -i <iface> -w <file> [ -f <filter> ]
```

You can grab it like this:

```bash
export GO111MODULE=on
go get github.com/gcla/termshark/v2/cmd/termshark@randpkt
```

**Comment by pocc** [comment]
This is not wise. dumpcap should be used by default because tshark introduces minor packet loss (~0.5-2.5%) by comparison.

**Comment by pocc** [comment]
Also, what does this mean in `--help`?

```
If --pass-thru is true (or auto, and stdout is not a tty), tshark will be
executed with the supplied command-line flags.
```

Is that tshark or actually the default capturing command?

**Comment by gcla** [comment]
> This is not wise. dumpcap should be used by default because tshark introduces minor packet loss (~0.5-2.5%) by comparison.

Ok - think a FAQ entry would suffice? Or I suppose termshark could start with dumpcap and fall back to tshark if it can figure out that's the only way to get the synthetic live capture sources..?

**Comment by gcla** [comment]
> Also, what does this mean in `--help`?
> 
> ```
> If --pass-thru is true (or auto, and stdout is not a tty), tshark will be
> executed with the supplied command-line flags.
> ```
> 
> Is that tshark or actually the default capturing command?

The idea here was to just exec tshark if stdout is not a tty e.g.

```
termshark -r foo.pcap | less
    1   0.000000 134.141.5.32 → 134.141.225.136 TLSv1 1123 Server Hello, Certificate, Server Key Exchange, Server Hello Done
(END)
```
So you could use termshark just like tshark if you're invoking it in a pipeline. Termshark passes the args right through. The `--pass-thru` argument allows you to explicitly control this behavior.

**Comment by pocc** [comment]
> The idea here was to just exec tshark if stdout is not a tty e.g.

Do people use this or have they asked for this functionality? This seems counter to termshark's purpose (provide a TUI to tshark to my understanding). I'm trying to think of a situation where I would want termshark output without just using tshark.

>> This is not wise. dumpcap should be used by default because tshark introduces minor packet loss (~0.5-2.5%) by comparison.
>
> Ok - think a FAQ entry would suffice? Or I suppose termshark could start with dumpcap and fall back to tshark if it can figure out that's the only way to get the synthetic live capture sources..?

Changed issue to feature request (see initial post).

**Comment by gcla** [comment]
> > The idea here was to just exec tshark if stdout is not a tty e.g.
> 
> Do people use this or have they asked for this functionality? This seems counter to termshark's purpose (provide a TUI to tshark to my understanding). I'm trying to think of a situation where I would want tshark output without just using tshark.

Just my idea :) I don't know which parts of termshark most folks use, generally. But I do like interactive programs that behave usefully when stdout is not a tty e.g. `less` will behave like `cat` if stdout is not a tty. Seemed reasonable to me to fall back to tshark inside a pipeline. Are you finding that feature gets in the way?

**Comment by pocc** [comment]
> But I do like interactive programs that behave usefully when stdout is not a tty

I feel like this is a problem though. You're catching an error for unexpected behavior and then... not erroring. The user doesn't know to correct their usage mistake. `less` has a better use case for this behavior, but it's still hiding an error:

```bash
# These are both equivalent
echo 'some words' | less | cat
echo 'some words' | cat
```

`less` not erroring hides the fact that it is essentially a noop. Likewise, termshark not erroring here doesn't alert users that they should use tshark instead.

At the end of the day though, this question is a matter of opinion, and not worth acting upon if you like this behavior.

**Comment by gcla** [comment]
Thanks. I do appreciate the opinion.

The current termshark behavior does seem less useful than what less does. At work I quite often find myself with less in a pipeline. Something like

```
cat foo | sort blah | grep blah | sed blah | less
# nope, up arrow
cat foo | sort blah | grep blah | sed blah | less | grep -v xyz | less
...
```

I suppose I mean less is very often used in a pipeline, and it's convenient to just stick some more filters on the end of what you have without having to cut less off first. Can't really say termshark is used in that way. I have never written a pipeline like this

```
blah | termshark
# oops, up arrow
blah | termshark | grep -v abc | termshark
```

Doesn't make sense - but maybe it would make more sense if `termshark | ` passed through packets in pcap format like `tshark -w /dev/stdout`...

```
cat foo.pcap | termshark
# look at tui, nope not right, up arrow
cat foo.pcap | termshark -Y 'tcp.port = 80'
# look at tui, yes correct, q then up arrow
cat foo.pcap | termshark -Y 'tcp.port = 80' | cat > foo2.pcap
```

Anyway, I'll chew on this.

Will try to work on your dumpcap/tshark fallback soon.

**Comment by pocc** [comment]
Another option here is to check the interface list on error to include better error information. So if tshark's interfaces has this interface (by number or by name), but not dumpcap, let the user know. Something like

> Entered $interface is a virtual interface. The current pcap reader is dumpcap, which does not understand virtual interfaces. To use $interface, change the default dumpcap in your config file to tshark.
>
> More information on config files can be found in the user guide: https://github.com/gcla/termshark/blob/master/docs/UserGuide.md#config-file."

**Comment by gcla** [comment]
Hello - I've pushed a new branch, `extcap`. Built from this branch, termshark - on Unix - will use a hybrid method to capture packets:

- it will run `dumpcap` first, or the binary configured in `termshark.toml` as `main.dumpcap`
- if that fails, it will exec `tshark`, or the binary configured in `termshark.toml` as `main.tshark`

The idea is to use dumpcap if possible, since it is more efficient and less likely to drop packets, but fall back to tshark if there's an error, such as trying to use dumpcap with an extcap interface.

There's a new toml config option `main.capture-command` which defaults to `termshark` on Unix - meaning to capture, termshark runs itself, but with a special env variable `TERMSHARK_CAPTURE_MODE=1` set. At startup, termshark checks that early and redirects to its capture function. You could use a simple shell script to achieve the same effect, but I wanted to keep termshark as a single binary without the need for extra things to be installed. 

If this approach works for you, do let me know - or if it doesn't too :-) Build like this:

```bash
export GO111MODULE=on
go get github.com/gcla/termshark/v2/cmd/termshark@extcap
```

As usual, I have to admit sheepishly that I haven't tried this on macOS, only Linux and Windows...

**Comment by pocc** [comment]
Getting errors on macos/linux that look similar (go1.13):

## Macos

```bash
mbp:tmp rj$ bash build.sh
Fetching origin
HEAD is now at 7e72a37 Update CHANGELOG with a note about extcap interfaces
./termshark: line 1: syntax error near unexpected token `newline'
./termshark: line 1: `!<arch>'
```

## Linux

```bash
$ sudo ./termshark -i randpkt
./termshark: 2: ./termshark: Syntax error: newline unexpected
```

## Setup script

```bash
#!/usr/bin/env bash
# Install the extcap branch of termshark and run it
export GO111MODULE=on
cd $HOME/go/src/github.com/gcla/termshark
git fetch --all
git checkout extcap
go build -o termshark
chmod a+x termshark
sudo ./termshark
```

I'll check linux to see if it's just this computer being weird.

**Comment by gcla** [comment]
Thanks @pocc - I didn't try with sudo, and now I see the same problem... More soon

**Comment by gcla** [comment]
Hi again - I've pushed some new commits to extcap. Let me know if they resolve the issue. Slight note of caution - I managed to delete my OS /dev/null(!) - pretty sure I resolved that problem, it came down to running this with euid=0, which I now no longer do:

```
dumpcap -i randpkt -a duration:1 -w /dev/null
```

**Comment by pocc** [comment]
I mean no loss - this /dev/null thing did nothing when you sent it messages anyway. Better to just get rid of it altogether.

**Comment by pocc** [comment]
Your commit messages are a thing to be admired. :-)

**Comment by pocc** [comment]
Still getting the same genre of error when dumpcap is set up requiring sudo:

```bash
rj@vmbuntu:~/code/termshark$ go build -o termshark; chmod a+x ./termshark; sudo ./termshark
./termshark: 2: ./termshark: Syntax error: newline unexpected
rj@vmbuntu:~/code/termshark$ go build -o termshark; chmod a+x ./termshark; ./termshark
./termshark: line 1: syntax error near unexpected token `newline'
./termshark: line 1: `!<arch>'
```

Also getting this under root:

```bash
root@vmbuntu# ./termshark
./termshark: line 1: syntax error near unexpected token `newline'
./termshark: line 1: `!<arch>'
```

It looks like I'm on the right commit: 

```bash
rj@vmbuntu:~/code/termshark$ git rev-parse --short HEAD
bc28fc6
```

**Comment by gcla** [comment]
hi - had to google for this one! :)

I think the issue is that this command:

```
go build -o termshark
```

is building a library instead of the command-line binary (a sort of `libtermshark.a` I suppose). Could you try this command instead:

```
go install ./...
```

Then the binary should be in `~/go/bin/`

This is what I see on my Ubuntu machine:

```
$ go install ./...
$ sudo /home/gcla/go/bin/termshark
(The termshark UI will start when packets are detected...)
^CPackets read from eth0 have been saved in /root/.cache/termshark/pcaps/eth0--2020-01-29--22-46-47.pcap
```

**Comment by pocc** [comment]
Ah thank you! It's nice when it's something simple like that.

Extcap interfaces clearly work on both macos & linux - great work here!
